---
apiVersion: v1
kind: Pod
metadata:
  name: pod-1-webserver1
  namespace: facebook
  labels:
    role: web-service
    app: V1
    

spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: pod2-webserver2
  namespace: facebook
  labels:
    role: web-service
    app: V2

spec:
  containers:
    - name: nginx2
      image: nginx:alpine
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: pod3-webserver3
  namespace: facebook
  labels:
    role: web-service
    app: V3

spec:
  containers:
    - name: nginx
      image: nginx:1.27
      ports:
        - containerPort: 80


---
apiVersion: v1
kind: Pod
metadata:
  name: pod4-webserver4
  namespace: facebook
  labels:
    role: web-service
    app: V4

spec:
  containers:
    - name: nginx
      image: nginx:1.26.3
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: web-service1
  namespace: facebook

spec:
  selector:
    app: V1
  type: LoadBalancer
  ports:
    - port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: web-service2
  namespace: facebook

spec:
  selector:
    app: V2
  type: LoadBalancer
  ports:
    - port: 80
    
---
apiVersion: v1
kind: Service
metadata:
  name: web-service3
  namespace: facebook

spec:
  selector:
    app: V3
  type: LoadBalancer
  ports:
    - port: 80
    
---
apiVersion: v1
kind: Service
metadata:
  name: web-service4
  namespace: facebook

spec:
  selector:
    app: V4
  type: LoadBalancer
  ports:
    - port: 80